version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: notes-mongodb
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
    # Optional: If you want to set up authentication
      MONGO_INITDB_DATABASE: notesdb_dev # This sets the default database when you connect
    healthcheck:
      test: |
        echo "try { rs.status() } catch (err) { rs.initiate() }" | mongosh --quiet
      interval: 5s
      timeout: 30s
      retries: 30

volumes:
  mongodb_data:
